### ISSUE TITLE
Does it also work for the H707 ?

### ISSUE THREAD

**Issue by pardeepmg** [Fitpolo/FitpoloDemo_H706_Android#1]
I am looking sdk for th H707 device but could not find. I tried FitpoloDemo_H706_Android, its connecting successfully but not returning accurate data. Not even nearby data. 

So would it work for H707 ? Or do you have other reference sdk for H707?

**Comment by liuwenzheng** [comment]
Yes,it work for H707.Which order has error?

**Comment by pardeepmg** [comment]
No its not working for the H707 Device, i changed 
` if (!"06".equals(DigitalConver.byte2HexString(manufacturerSpecificData[4]))) {
                return;
            }` to 
` if (!"07".equals(DigitalConver.byte2HexString(manufacturerSpecificData[4]))) {
                return;
            }`
After that it connects with device but not providing any data. Then i tried your demo with H706 and it works successfully with that and providing data also.

**Comment by pardeepmg** [comment]
But its not working with H707, i tried to change the sdk code too but nothing worked.

**Comment by liuwenzheng** [comment]
Sorry, we made a mistake. We uploaded the SDK of H707, and the path is as follows:
https://github.com/Fitpolo/FitpoloDemo_H707_Android.git

**Comment by pardeepmg** [comment]
Thanks. One more thing i would like to ask, would it be different sdk for different versions for devices?
As fitpolo offical App works for all version and even iOS sdk also works irrespective of the version.

**Comment by liuwenzheng** [comment]
Each version of the SDK is isolated from the source code and can be easily distinguished by the user. If you need to be compatible with different devices, you can put them together.

**Comment by liuwenzheng** [comment]
Each version of the SDK is split from the source code and can be easily identified by the user. If you need to be compatible with different devices, you can put them together.
