### ISSUE TITLE
What is the purpose of HEART_RATE_NOTIFY ? 

### ISSUE THREAD

**Issue by theapache64** [Fitpolo/FitpoloDemo_H706_Android#4]
Hi,

I've seen that there's a `OrderEnum` named `HEART_RATE_NOTIFY`. What does it do ? Can it be used to monitor heart rate?

**Comment by liuwenzheng** [comment]
No, we don't support this yet. You can only read it actively

**Comment by theapache64** [comment]
Duplicate of #2
