### ISSUE TITLE
how do i get all sport records?

### ISSUE THREAD

**Issue by Kalaras** [Fitpolo/FitpoloDemo_H706_Android#5]
I need to get all the sports records of the device, but with `ZReadSportsTask` i only get the data of the day. Is there any way to do in only one order to device?

**Comment by liuwenzheng** [comment]
'ZReadSportsTask(MokoOrderTaskCallback callback, Calendar lastSyncTime)'

You can set the 'lastSyncTime' to 2000-01-01 so that all data after that point is returned to you
